@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onefile --console --icon "%~dp0wave-sound [256x256].ico" --optimize "2" --exclude-module "chardet" --exclude-module "auto-py-to-exe" --exclude-module "pyright" --exclude-module "pyarmor"  "%~dp0rew_converter\rew_converter.py"
pause
