@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --icon "C:\Users\hc40745164\Documents\Projetos_Pythons\rew-converter\wave-sound [256x256].ico" "rew_converter\rew_converter.py"
pause
